"""Utilities for exporting adoption results to PyPSA-Earth.

This module merges node metadata from ``results/buses.csv`` with
technology adoption metrics produced by
:func:`technology_adoption_model.generate_adoption_tables`. The combined
information can be attached to a PyPSA ``Network`` when preparing inputs
for the PyPSA-Earth workflow.

Example
-------
>>> import pypsa
>>> import pypsa_export as pe
>>> n = pypsa.Network("path/to/network.nc")
>>> pe.attach_adoption_data(n, "bau", 2030)
>>> n.export_to_csv_folder("results/pypsa_network")
"""

from __future__ import annotations

import os
import pandas as pd


def _load_bus_metadata() -> pd.DataFrame:
    """Read bus metadata generated by :mod:`spatial_config`."""
    return pd.read_csv(os.path.join("results", "buses.csv"))


def _load_adoption(scenario: str) -> pd.DataFrame:
    """Read adoption metrics for a given scenario."""
    path = os.path.join("results", f"adoption_{scenario}.csv")
    return pd.read_csv(path)


def attach_adoption_data(network, scenario: str, year: int):
    """Attach adoption data and household counts to a PyPSA network.

    Parameters
    ----------
    network : pypsa.Network
        Loaded PyPSA network object whose ``buses`` will be annotated.
    scenario : str
        Scenario name corresponding to an ``adoption_<scenario>.csv`` file.
    year : int
        Year to select from the adoption and bus tables.

    Returns
    -------
    pypsa.Network
        The network with additional columns for ``urban_hh``, ``rural_hh``
        and adoption metrics (``technology``, ``share`` and ``energy_GJ``)
        merged onto its ``buses`` DataFrame.
    """

    buses = _load_bus_metadata()
    adoption = _load_adoption(scenario)
    buses_year = buses[buses["year"] == year]
    adoption_year = adoption[adoption["year"] == year]
    merged = buses_year.merge(adoption_year, on=["region", "year"], how="left")
    network.buses = network.buses.merge(
        merged.set_index("region"), left_on="name", right_index=True, how="left"
    )
    return network
